#!/usr/bin/env bash

	 echo "initialize" \
&& rm -rf pack \
&& echo "compile once (succeeds)" \
&& scalac-2.9 src/main/scala/pack/age/Foo.scala src/main/scala/pack/age/Bar.scala \
&& echo "compile again (fails)" \
&& scalac-2.9 src/main/scala/pack/age/Foo.scala src/main/scala/pack/age/Bar.scala

